### ISSUE TITLE
Stage 1: Main Structure Setup

### ISSUE THREAD

**Issue by AshNumpy** [AshNumpy/Image-To-Data#2]
# Görevin Tanımı
Proje yapısını oluşturmak için temel dosya ve klasörleri düzenle. `main.py` gibi merkezi bir dosya oluştur ve modüllerin ayrılacağı klasör yapısını belirle.

## Alt Görevler
- [ ] Proje klasör yapısını oluştur.
- [ ] `main.py` dosyasını oluştur.
- [ ] Modüllerin yer alacağı `modules/` klasörünü oluştur.

## Milestone 
**Milestone 1: Proje Yapısının Kurulması**

## Tags
`setup`, `structure`, `organization`
