### ISSUE TITLE
Stage 2: Image Preprocessing Module

### ISSUE THREAD

**Issue by AshNumpy** [AshNumpy/Image-To-Data#3]
# Görevin Tanımı
Görüntü işleme için gerekli modülü oluştur. Bu modülde görüntüyü threshold ve dilate etme işlemleri yapılacak. Bu modül için kodları modüler bir şekilde yaz.

## Alt Görevler
- [ ] `image_preprocessing.py` dosyasını oluştur.
- [ ] Resmi `threshold` işleminden geçir.
- [ ] Dilate işlemi ile kelimeleri blob'lara dönüştür.

## Milestone 
**Milestone 2: Görüntü İşleme**

## Tags
`image processing`, `threshold`, `dilate`
