### ISSUE TITLE
Stage 4: Bounding Boxes Sorting and Row/Column Grouping

### ISSUE THREAD

**Issue by AshNumpy** [AshNumpy/Image-To-Data#5]
# Görevin Tanımı
Bounding box'ları satır ve sütunlara göre ayır. Önce Y koordinatına göre sıralama, sonra X'e göre sıralama yaparak tablo düzenini oluştur.

## Alt Görevler
- [ ] Bounding box'ların yükseklik ortalamasını hesapla.
- [ ] Bounding box'ları satır/sütun bazlı grupla.
- [ ] Her bir satırı X koordinatına göre sırala.

## Milestone 
**Milestone 4: Tablonun Gruplandırılması**

## Tags
`sorting`, `bounding boxes`, `row grouping`
