### ISSUE TITLE
Stage 7: Streamlit UI Integration

### ISSUE THREAD

**Issue by AshNumpy** [AshNumpy/Image-To-Data#8]
# Görevin Tanımı
Projenin son aşamasında Streamlit arayüzü oluşturarak kullanıcının bir resim yükleyip, tabloları CSV'ye dönüştürmesini sağlayan bir UI oluştur.

## Alt Görevler
- [ ] Streamlit ile arayüz oluştur.
- [ ] Resim yükleme fonksiyonunu ekle.
- [ ] Çıktıları CSV olarak export etme butonu ekle.

## Milestone 
**Milestone 7: UI Oluşturma ve Kullanıcı Etkileşimi**

## Tags
`UI`, `Streamlit`, `export`
